version: '3.7'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
  gateway:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    command: gateway s3 http://minio1:9000
    restart: always
    ports:
      - 9002:9000
    environment:
      MINIO_ACCESS_KEY: d989f4bc38e868ded161eb829afa7766
      MINIO_SECRET_KEY: 61e88a20d78de005e399a354196025dc0135483b
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  proxy:
    image: nginx:latest
    restart: always
    ports:
      - 9001:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/ca
  minio1:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    # image: minio/minio:RELEASE.2020-04-22T00-11-12Z
    command: server http://minio{1...4}/data{1...2}
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    environment:
      MINIO_ACCESS_KEY: d989f4bc38e868ded161eb829afa7766
      MINIO_SECRET_KEY: 61e88a20d78de005e399a354196025dc0135483b
      # MINIO_ACCESS_KEY_OLD: d989f4bc38e868ded161eb829afa7766a
      # MINIO_SECRET_KEY_OLD: 61e88a20d78de005e399a354196025dc0135483b
      MINIO_BROWSER: "off"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  minio2:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    # image: minio/minio:RELEASE.2020-04-22T00-11-12Z
    command: server http://minio{1...4}/data{1...2}
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    environment:
      MINIO_ACCESS_KEY: d989f4bc38e868ded161eb829afa7766
      MINIO_SECRET_KEY: 61e88a20d78de005e399a354196025dc0135483b
      # MINIO_ACCESS_KEY_OLD: d989f4bc38e868ded161eb829afa7766a
      # MINIO_SECRET_KEY_OLD: 61e88a20d78de005e399a354196025dc0135483b
      MINIO_BROWSER: "off"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  minio3:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    # image: minio/minio:RELEASE.2020-04-22T00-11-12Z
    command: server http://minio{1...4}/data{1...2}
    volumes:
      - data3-1:/data1
      - data3-2:/data2
    environment:
      MINIO_ACCESS_KEY: d989f4bc38e868ded161eb829afa7766
      MINIO_SECRET_KEY: 61e88a20d78de005e399a354196025dc0135483b
      # MINIO_ACCESS_KEY_OLD: d989f4bc38e868ded161eb829afa7766a
      # MINIO_SECRET_KEY_OLD: 61e88a20d78de005e399a354196025dc0135483b
      MINIO_BROWSER: "off"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    # image: minio/minio:RELEASE.2020-04-22T00-11-12Z
    command: server http://minio{1...4}/data{1...2}
    volumes:
      - data4-1:/data1
      - data4-2:/data2
    environment:
      MINIO_ACCESS_KEY: d989f4bc38e868ded161eb829afa7766
      MINIO_SECRET_KEY: 61e88a20d78de005e399a354196025dc0135483b
      # MINIO_ACCESS_KEY_OLD: d989f4bc38e868ded161eb829afa7766a
      # MINIO_SECRET_KEY_OLD: 61e88a20d78de005e399a354196025dc0135483b
      MINIO_BROWSER: "off"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
